"""
00_reset.py
-----------
Resets the pipeline back to the state after step 01 (image tiling), so that
steps 02 → 05 can be re-run with different parameters without re-tiling.

WHAT THIS SCRIPT UNDOES
────────────────────────
  Step 02  –  deletes all label .txt files in labels/{train,val,test}/
  Step 03  –  moves images from val/, test/, and archive/ back to train/
  Step 04  –  same as above (archive/ consolidation)
  Step 05  –  no-op: in-place upsampled images cannot be reversed
              (a warning is printed if upsampled images are detected)

WHAT IS PRESERVED
──────────────────
  data/processed/images/train/  ← all tile PNGs end up here (restored)
  data/processed/metadata.csv   ← untouched

WHAT IS DELETED
────────────────
  data/processed/labels/        ← regenerated by step 02
  data/processed/archive/labels/

After running this script the folder state is identical to what step 01
produced, and scripts 02 → 05 can be re-run cleanly.
"""

import shutil
from pathlib import Path


# =============================================================================
# CONFIGURATION
# =============================================================================

PROCESSED_DIR = "data/processed"

# If True, print every file move/delete.  Set False for quieter output.
VERBOSE = False

# =============================================================================


def _move(src: Path, dst: Path, moved: list) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        # Name collision — the same tile stem exists in two places.
        # Keep the one already in train/ (already consolidated); skip.
        return
    shutil.move(str(src), str(dst))
    moved.append(src.name)
    if VERBOSE:
        print(f"    MOVE  {src}  →  {dst}")


def _delete_dir(path: Path, deleted: list) -> None:
    if path.exists():
        count = sum(1 for _ in path.rglob("*") if _.is_file())
        shutil.rmtree(path)
        deleted.append(f"{path}  ({count} file(s))")
        if VERBOSE:
            print(f"    DELETE  {path}  ({count} file(s))")


def main():
    base      = Path(PROCESSED_DIR)
    train_img = base / "images" / "train"
    train_img.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("  Pipeline Reset  (restoring state after step 01)")
    print("=" * 60)

    # ──────────────────────────────────────────────────────────────
    # 1.  Gather images from val/ and test/ back into train/
    # ──────────────────────────────────────────────────────────────
    print("\n[1/4]  Consolidating images -> images/train/ ...")
    total_moved_img = []

    for split in ("val", "test"):
        split_dir = base / "images" / split
        if not split_dir.exists():
            continue
        pngs = list(split_dir.glob("*.png"))
        for png in pngs:
            _move(png, train_img / png.name, total_moved_img)
        # Remove the now-empty directory
        try:
            split_dir.rmdir()
        except OSError:
            pass   # not empty -> leave it

    print(f"    Moved {len(total_moved_img)} image(s) from val/ + test/")

    # ──────────────────────────────────────────────────────────────
    # 2.  Restore archived images (from steps 03 & 04) to train/
    # ──────────────────────────────────────────────────────────────
    print("\n[2/4]  Restoring archived images -> images/train/ ...")
    archived_moved = []

    for split in ("train", "val", "test"):
        arch_img = base / "archive" / "images" / split
        if not arch_img.exists():
            continue
        for png in arch_img.glob("*.png"):
            _move(png, train_img / png.name, archived_moved)
        try:
            arch_img.rmdir()
        except OSError:
            pass

    print(f"    Restored {len(archived_moved)} archived image(s)")

    # ──────────────────────────────────────────────────────────────
    # 3.  Delete all label files (step 02 output)
    # ──────────────────────────────────────────────────────────────
    print("\n[3/4]  Deleting label files ...")
    deleted_dirs = []

    _delete_dir(base / "labels", deleted_dirs)
    _delete_dir(base / "archive" / "labels", deleted_dirs)

    # Clean up leftover archive skeleton if now entirely empty
    archive_dir = base / "archive"
    if archive_dir.exists():
        remaining = list(archive_dir.rglob("*"))
        if not any(p.is_file() for p in remaining):
            shutil.rmtree(archive_dir)
            if VERBOSE:
                print(f"    REMOVE (empty)  {archive_dir}")

    if deleted_dirs:
        for d in deleted_dirs:
            print(f"    Deleted  {d}")
    else:
        print("    Nothing to delete.")

    # ──────────────────────────────────────────────────────────────
    # 4.  Upsampling check (step 05 is in-place — cannot be reversed)
    # ──────────────────────────────────────────────────────────────
    print("\n[4/4]  Checking for upsampled images (step 05) ...")
    try:
        import cv2
        sample_pngs = list(train_img.glob("*.png"))[:10]
        sizes = set()
        for p in sample_pngs:
            img = cv2.imread(str(p), cv2.IMREAD_COLOR)
            if img is not None:
                sizes.add(img.shape[0])
        if sizes and max(sizes) > 768:
            print(f"    WARNING: images appear to be {max(sizes)}px (already upsampled).")
            print(f"    In-place upsampling (step 05) cannot be reversed.")
            print(f"    If you need original 768px tiles, re-run step 01.")
        else:
            print(f"    OK  Images are at original tile size — step 05 not yet applied.")
    except ImportError:
        print("    (cv2 not available — skipping size check)")

    # ──────────────────────────────────────────────────────────────
    # Summary
    # ──────────────────────────────────────────────────────────────
    total_train = len(list(train_img.glob("*.png")))

    print(f"\n{'='*60}")
    print(f"  Reset complete.")
    print(f"{'='*60}")
    print(f"  images/train/      : {total_train} tile(s) ready")
    print(f"  Images moved       : {len(total_moved_img) + len(archived_moved)}")
    print(f"  Label dirs removed : {len(deleted_dirs)}")
    print()
    print("  You can now re-run the pipeline from step 02:")
    print("    python 02_geojson_to_txt.py")
    print("    python 03_split_dataset.py")
    print("    python 04_downsample_background.py")
    print("    python 05_upsample.py")
    print()


if __name__ == "__main__":
    main()
